In [2]:
from matplotlib import pyplot as plt
from tifffile import tifffile

"""full 1 channel tiff writer without dataframe log"""



def create_marked_file_final(xml_file, input_file, output_file):
    import numpy as np
    import tifffile
    import xml.etree.ElementTree as ET

    original_image = tifffile.imread(input_file)
    layers, channels, height, width = original_image.shape
    print(original_image.shape)
    binary_image = np.zeros((layers, 1, height, width), dtype=np.uint8)
    tree = ET.parse(xml_file)
    root = tree.getroot()
    for marker_type in root.findall('Marker_Data/Marker_Type'):
        type_id = int(marker_type.find('Type').text)

        for marker in marker_type.findall('Marker'):

            x = int(marker.find('MarkerX').text) -1
            y = int(marker.find('MarkerY').text) -1
            z_raw = ((int(marker.find('MarkerZ').text) + 2 ) // 3) -1

            binary_image[z_raw, 0, y, x] = 255

    tifffile.imwrite(output_file, binary_image)
    return binary_image


create_marked_file_final('FF15A/CellCounter_FF151L2L.xml', 'FF15/FF151L2L.lsm', 'FF15/FF151L2L_marked7.tif')



(56, 3, 512, 512)


array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       ...,


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 

In [19]:
"""Full dataframe logger from xml file"""



def pull_marker_data(xml_file):
    import xml.etree.ElementTree as et
    import pandas as pd
    file = et.parse(xml_file)
    root = file.getroot()
    marker_data = []

    MDElement = root.find('Marker_Data')
    for Marker_Type in MDElement.findall('Marker_Type'):
        type_id = int(Marker_Type.find('Type').text)

        for Marker in Marker_Type.findall('Marker'):
            xloc = int(Marker.find('MarkerX').text) if Marker.find('MarkerX') is not None else None
            yloc = int(Marker.find('MarkerY').text) if Marker.find('MarkerY') is not None else None
            zloc = int(Marker.find('MarkerZ').text) if Marker.find('MarkerZ') is not None else None
            zlayer = (2 + zloc) // 3

            marker_data.append({
                'z': zlayer,
                'type_id': type_id,
                'y': yloc,
                'x': xloc,
            })

    dataframe = pd.DataFrame(marker_data, columns=['z', 'type_id', 'y', 'x'])
    return dataframe

result = pull_marker_data('FF15A/CellCounter_FF151L2L.xml')
result.head(96)

z  type_id    y    x
0   11        1  206  115
1   11        1  213  114
2   11        1  229   99
3   11        1  226   82
4   11        1  223   80
..  ..      ...  ...  ...
91  32       10  356  268
92  32       10  354  271
93  32       10  363  259
94  32       10  385  258
95  32       10  385  249

[96 rows x 4 columns]

In [4]:
result = pull_marker_data('FF15/CellCounter_FF151L2L_marked92.xml')
result.head(96)

z  type_id    y    x
0  13        1   80  249
1  13        1   85  250
2  13        1   93  246
3  13        1  107  232
4  13        1  108  227
5  13        1   74  245

In [28]:
"""full 1 channel tiff writer from dataframe log"""


def pull_synapse_and_mark_file(xml_file, input_file, output_file):
    import numpy as np
    import tifffile

    df = pull_marker_data(xml_file)

    original_image = tifffile.imread(input_file)
    layers, channels, height, width = original_image.shape
    binary_image = np.zeros((layers, 1, height, width), dtype=np.uint8)

    x = df['x']
    y = df['y']
    z = df['z']

    for i in range(len(df)):
        binary_image[z[i] - 1,:, y[i] - 1, x[i] - 1] = 255

    tifffile.imwrite(output_file, binary_image)
    return binary_image

# Example usage
pull_synapse_and_mark_file('FF15A/CellCounter_FF151L2L.xml', 'FF15/FF151L2L.lsm', 'FF15/FF151L2L_marked93.tif')

array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       ...,


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 

In [2]:
"""full 3 channel tiff writer without dataframe log"""

def create_colored_file_final(xml_file, input_file, output_file):
    import numpy as np
    import tifffile
    import xml.etree.ElementTree as ET

    original_image = tifffile.imread(input_file)
    layers, channels, height, width = original_image.shape
    print(original_image.shape)
    rgb_image = np.zeros((layers, 3, height, width), dtype=np.uint8)
    tree = ET.parse(xml_file)
    root = tree.getroot()
    typecount = 0
    for marker_type in root.findall('Marker_Data/Marker_Type'):
        typecount += 1
        continue
    type_array = []
    start_color = np.array([255, 0, 0])
    end_color = np.array([0, 0, 255])
    for i in range(typecount):
        color = (start_color + (end_color - start_color) * i / (typecount - 1)).astype(int)
        type_array.append(tuple(color))
    for marker_type in root.findall('Marker_Data/Marker_Type'):
        type_id = int(marker_type.find('Type').text)
        if type_id <= typecount // 2:
            color = (
                np.array([255, 0, 0]) + (np.array([0, 255, 0]) - np.array([255, 0, 0])) * type_id / (typecount - 1)
            ).astype(int)
        else:
            color = (
                np.array([0, 255, 0]) + (np.array([0, 0, 255]) - np.array([0, 255, 0])) * (type_id - (typecount // 2)) / (typecount - 1)
            ).astype(int)

        for marker in marker_type.findall('Marker'):

            x = int(marker.find('MarkerX').text) - 1
            y = int(marker.find('MarkerY').text) - 1
            z = ((int(marker.find('MarkerZ').text) + 2) // 3) - 1

            rgb_image[z, :, y, x] = color  # Apply color to all three channels for the specific pixel

    tifffile.imwrite(output_file, rgb_image)
    return rgb_image


create_colored_file_final('FF15A/CellCounter_FF151L2L.xml', 'FF15/FF151L2L.lsm', 'FF15/FF151L2L_marked72.tif')

(56, 3, 512, 512)


array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
  

In [23]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_3d_nonzero_pixels(image):
    z, c, y, x


SyntaxError: unterminated triple-quoted string literal (detected at line 19) (1714432801.py, line 19)

In [20]:
""" create the most distinct colors from the dataframe"""



def find_distinct_colors(xml_file):
    import numpy as np
    import colorsys

    df = pull_marker_data(xml_file)
    num_colors = max(df['type_id'])

    colors = []
    for i in range(num_colors):
        r, g, b = colorsys.hsv_to_rgb(i / num_colors, 1.0, 1.0)
        rgb = np.array([int(r * 255), int(g * 255), int(b * 255)])
        colors.append(rgb)

    return colors


print(find_distinct_colors('FF15A/CellCounter_FF151L2L.xml'))




[array([255,   0,   0]), array([255, 153,   0]), array([203, 255,   0]), array([ 51, 255,   0]), array([  0, 255, 102]), array([  0, 255, 255]), array([  0, 102, 255]), array([ 50,   0, 255]), array([204,   0, 255]), array([255,   0, 152])]


In [11]:
"""full 3 channel hue color tiff writer from dataframe log"""

"full working code readable on napari image viewer"

def pull_synapse_and_mark_file(xml_file, input_file, output_file):
    import numpy as np
    import tifffile
    df = pull_marker_data(xml_file)
    color_array = find_distinct_colors(xml_file)
    original_image = tifffile.imread(input_file)
    layers, channels, height, width = original_image.shape
    rgb_image = np.zeros((layers, 3, height, width), dtype=np.uint8)
    x = df['x']
    y = df['y']
    z = df['z']
    type_id = df['type_id']
    for i in range(len(df)):
        rgb_image[z[i] -1, :, y[i] -1, x[i] -1] = color_array[type_id[i] -1]
    tifffile.imwrite(output_file, rgb_image)
    return rgb_image

pull_synapse_and_mark_file('FF15A/CellCounter_FF151L2L.xml', 'FF15/FF151L2L.lsm', 'FF15/FF151L2L_marked92.tif')




array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],


       [[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
  

In [18]:
"image marking reader"

import tifffile
import numpy as np  # Make sure numpy is imported

image = tifffile.imread('FF15/FF151L2L_marked92.tif')
# og = tifffile.imread('FF15/FF151L2L.lsm') # This line is not strictly needed for the current request

print("Image shape:", image.shape)
# print("Original LSM shape:", og.shape) # Not strictly needed for the current request

# Find the indices of non-zero elements
indices_of_non_zero = np.nonzero(image)

# Extract z, y, x coordinates based on the image shape
# z corresponds to layers (dimension 0)
# y corresponds to height (dimension 2)
# x corresponds to width (dimension 3)
z_coords = indices_of_non_zero[0]
y_coords = indices_of_non_zero[2]
x_coords = indices_of_non_zero[3]

if z_coords.size > 0:  # Check if there are any non-zero values
    # Stack the spatial coordinates: each row becomes [z, y, x]
    all_hit_spatial_coords = np.stack((z_coords, y_coords, x_coords), axis=1)

    # Find unique spatial coordinates (unique rows of [z, y, x])
    unique_spatial_coordinates = np.unique(all_hit_spatial_coords, axis=0)

    print(
        f"\nFound {len(unique_spatial_coordinates)} unique (z, y, x) spatial locations with non-zero values in the 'image':")

    # Print all unique coordinates directly
    for coord in unique_spatial_coordinates:
        print(f"z: {coord[0]}, y: {coord[1]}, x: {coord[2]}")
else:
    print("\nNo non-zero values found in the 'image'.")


Image shape: (56, 3, 512, 512)

Found 96 unique (z, y, x) spatial locations with non-zero values in the 'image':
z: 10, y: 58, x: 431
z: 10, y: 61, x: 410
z: 10, y: 67, x: 428
z: 10, y: 69, x: 426
z: 10, y: 76, x: 424
z: 10, y: 85, x: 395
z: 10, y: 92, x: 397
z: 10, y: 92, x: 414
z: 10, y: 93, x: 411
z: 10, y: 182, x: 108
z: 10, y: 189, x: 101
z: 10, y: 192, x: 98
z: 10, y: 192, x: 112
z: 10, y: 199, x: 44
z: 10, y: 199, x: 112
z: 10, y: 202, x: 47
z: 10, y: 205, x: 79
z: 10, y: 205, x: 114
z: 10, y: 207, x: 48
z: 10, y: 210, x: 29
z: 10, y: 212, x: 113
z: 10, y: 218, x: 18
z: 10, y: 222, x: 79
z: 10, y: 225, x: 81
z: 10, y: 228, x: 98
z: 10, y: 230, x: 31
z: 10, y: 238, x: 27
z: 22, y: 446, x: 32
z: 22, y: 452, x: 27
z: 22, y: 452, x: 32
z: 22, y: 455, x: 36
z: 22, y: 460, x: 358
z: 22, y: 462, x: 34
z: 22, y: 464, x: 6
z: 22, y: 468, x: 29
z: 22, y: 469, x: 6
z: 22, y: 471, x: 375
z: 22, y: 473, x: 25
z: 22, y: 475, x: 345
z: 22, y: 479, x: 372
z: 22, y: 480, x: 345
z: 22, y: 484, x:

In [27]:
"""full 3 channel hue color 2d image folder writer from dataframe log"""


def create_rgb_image_folder(xml_file, input_file, output_folder):
    """Save each layer as individual RGB image instead of a single TIFF"""
    import numpy as np
    import tifffile
    import xml.etree.ElementTree as ET
    import os
    from PIL import Image

    # Create output folder if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)

    # Load original image and get dimensions
    original_image = tifffile.imread(input_file)
    layers, channels, height, width = original_image.shape
    print(f"Image shape: {original_image.shape}")

    # Create a binary mask for marked points
    binary_mask = np.zeros((layers, height, width), dtype=bool)

    # Parse XML to get marker coordinates
    tree = ET.parse(xml_file)
    root = tree.getroot()

    # Extract marker positions from XML
    for marker_type in root.findall('Marker_Data/Marker_Type'):
        for marker in marker_type.findall('Marker'):
            x = int(marker.find('MarkerX').text) - 1
            y = int(marker.find('MarkerY').text) - 1
            z_raw = ((int(marker.find('MarkerZ').text) + 2) // 3) - 1

            binary_mask[z_raw, y, x] = True

    # Save each layer as an RGB image
    for z in range(layers):
        # Create RGB image (height, width, 3)
        rgb_layer = np.zeros((height, width, 3), dtype=np.uint8)

        # Copy original image colors where marked
        for y in range(height):
            for x in range(width):
                if binary_mask[z, y, x]:
                    # Convert from (channel, y, x) to (y, x, channel) format
                    rgb_layer[y, x, :] = original_image[z, :, y, x]

        # Save the image
        img = Image.fromarray(rgb_layer)
        img.save(f"{output_folder}/layer_{z:03d}.png")

    return f"Saved {layers} images to {output_folder}"


# Example usage
create_rgb_image_folder('FF15A/CellCounter_FF151L2L.xml', 'FF15/FF151L2L.lsm', 'FF15/rgb_layers')




Image shape: (56, 3, 512, 512)


'Saved 56 images to FF15/rgb_layers'